// packages/reactjs/src/pages/example/index.tsx
import React from 'react'
import { Provider } from 'mobx-react'
import { RouteChildrenProps, withRouter } from 'react-router-dom'
import PageController, { PageEntity } from './controller'
import PageAction from './views/action'
import PageDetails from './views/details'
import PageFilter from './views/filter'
import PageGrid from './views/grid'
import { EnumPageMeta } from './locales'
@withRouter
export default class PageIndex extends React.Component<RouteChildrenProps> {
  static meta = EnumPageMeta;
  static PageController = PageController;
  static PageEntity = PageEntity;
  // 内部 this 访问
  readonly PageController = PageController;
  readonly PageEntity = PageEntity;
  state = {}
  componentDidMount() {
    React.$Mamba.Log.success(`Page [${EnumPageMeta.title}]`, this)
  }
  render() {
    return (
      <Provider PageController={PageController} PageEntity={PageEntity} >
        <PageFilter />
        <PageAction />
        <PageGrid />
        <PageDetails />
      </Provider>
    )
  }
}

// packages/vuejs/pages/example/index.vue
<template>
  <page-provider :PageController="PageController" :PageEntity="PageEntity">
    <ViewFilter />
    <ViewAction />
    <a-divider />
    <ViewGrid />
    <page-view width="1000px">
      <ViewDetails />
    </page-view>
  </page-provider>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import PageController, { PageEntity } from "./controller";
import { EnumPageMeta } from "./locales";
import ViewAction from "./views/action.vue";
import ViewDetails from "./views/details.vue";
import ViewFilter from "./views/filter.vue";
import ViewGrid from "./views/grid.vue";
@Component({
  meta: EnumPageMeta,
  components: {
    ViewAction,
    ViewFilter,
    ViewGrid,
    ViewDetails,
  },
})
export default class extends Vue {
  static PageController = PageController;
  static PageEntity = PageEntity;
  // 内部 this 访问
  readonly PageController = PageController;
  readonly PageEntity = PageEntity;
  created() { }
  mounted() {
    Vue.$Mamba.Log.success(`Page [${EnumPageMeta.title}]`, this)
  }
}
</script>
<style lang="less">
</style>
