// packages/reactjs/src/components/page/grid/index.tsx
import { ColDef, ColGroupDef, GridReadyEvent } from 'ag-grid-community';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-alpine.css';
import 'ag-grid-community/dist/styles/ag-theme-balham.css';
import 'ag-grid-community/dist/styles/ag-theme-material.css';
import { AgGridReact } from 'ag-grid-react';
import { AgGridReactProps } from 'ag-grid-react/lib/interfaces';
import lodash from 'lodash';
import { BindAll } from 'lodash-decorators';
import { observer } from 'mobx-react';
import React from 'react';
import { withRouter } from 'react-router-dom';
import { fromEvent, Subscription } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import defaultOptions from './defaultOptions';
import './style.less';
const theme: 'balham' | 'alpine' | 'material' = 'material'
const Grid = React.lazy<typeof AgGridReact>(() => import('./grid'))

interface IPageGridProps extends AgGridReactProps {
    // rowKey?: string;
    PageController?: React.BasesController;
    checkboxSelection?: boolean
}
// @observer
@BindAll()
export class PageGrid extends React.Component<IPageGridProps> {
    get PageController() {
        return this.props.PageController
    }
    state = { height: window.innerHeight - 250 }
    ref = React.createRef<HTMLDivElement>()
    ResizeEvent: Subscription;
    GridReadyEvent: GridReadyEvent;
    get disparity() {
        return { material: 160, alpine: 160, balham: 130 }[theme]
    }
    onAutoHeight() {
        try {
            this.GridReadyEvent?.api?.sizeColumnsToFit()
            const height = this.AppConfig.userAgent.isMobile ? window.innerHeight - this.disparity : window.innerHeight - this.ref.current.offsetTop - this.disparity
            this.setState({ height })
        } catch (error) {
            console.error("LENG ~  onAutoHeight", error)
        }
    }
    componentDidMount() {
        lodash.defer(() => {
            this.ResizeEvent = fromEvent(window, "resize")
                .pipe(debounceTime(300))
                .subscribe(this.onAutoHeight);
        })
    }
    componentWillUnmount() {
        this.ResizeEvent.unsubscribe()
    }
    getColumnDefs(columnDefs) {
        return lodash.concat(
            getColumnDefsCheckbox(this.props.checkboxSelection),
            columnDefs,
            getColumnDefsAction(this.props.frameworkComponents))
    }
    gridOptions: AgGridReactProps = {
        onGridReady: event => this.GridReadyEvent = event,
        getRowNodeId: data => lodash.get(data, this.PageController.options.dataKey),
        onSelectionChanged: event => this.PageController.Pagination.onSelectChange(event.api.getSelectedRows())
    }
    render() {
        const { columnDefs, ...props } = this.props;
        const gridOptions: AgGridReactProps = lodash.assign(
            {},
            defaultOptions(),
            props,
            this.gridOptions,
            { columnDefs: this.getColumnDefs(columnDefs) }
        )
        return (
            <div className="wt-ag-theme" ref={this.ref} >
                <React.Antd.Divider />
                <div className={`ag-theme-${theme}`} style={{ height: this.state.height }}>
                    <GridView {...gridOptions} PageController={this.PageController} />
                </div>
                <React.Antd.Divider />
                <PageGridPagination PageController={this.PageController} />
            </div>
        )
    }
}
@observer
@BindAll()
class GridView extends React.Component<IPageGridProps> {
    fallback() {
        return <div className="grid-skeleton">
            <React.Antd.ProSkeleton type="descriptions" pageHeader={false} />
        </div>
    }
    render() {
        const { PageController, ...props } = this.props;
        const { dataSource, loading } = PageController.Pagination;
        return (
            <React.Suspense fallback={this.fallback()}>
                <React.Antd.Spin spinning={loading}>
                    <Grid key={this.AppConfig.AppSettings.language} rowData={dataSource}  {...props} />
                </React.Antd.Spin>
            </React.Suspense>
        )
    }
}
@withRouter
@observer
@BindAll()
export class PageGridPagination extends React.Component<IPageGridProps> {
    get PageController() {
        return this.props.PageController
    }
    get Pagination() {
        return this.PageController.Pagination
    }
    get options() {
        return this.Pagination.PaginationParams
    }
    get current() {
        return this.Pagination.current
    }
    get pageSize() {
        return this.Pagination.pageSize
    }
    get total() {
        return this.Pagination.total
    }
    async onChange(current: number, pageSize?: number) {
        if (!current) {
            return console.warn('没有页码')
        }
        if (lodash.isEqual({ current: this.Pagination.current, pageSize: this.Pagination.pageSize }, { current, pageSize })) {
            return console.warn('页码没变化')
        }
        const url = this.$router.location.pathname;
        const oldQuery = this.$router.query;
        const query = lodash.assign({}, oldQuery, {
            [this.options.currentKey]: current,
            [this.options.pageSizeKey]: pageSize
        })
        if (lodash.eq(this.options.defaultPageSize, pageSize)) {
            lodash.unset(query, this.options.pageSizeKey)
        }
        const path = this.queryString.stringifyUrl({ url, query });
        await this.Pagination.onLoad({ current, pageSize });
        this.$router.history.replace(path)

    }
    componentDidMount() {
        // const oldQuery = this.$router.query;
        // this.onChange(oldQuery.current, oldQuery.pageSize)
    }
    render() {
        return (
            <React.Antd.Pagination
                // disabled={this.Pagination.loading}
                size={{ material: 'default', alpine: 'small', balham: 'small' }[theme] as any}
                simple={this.AppConfig.userAgent.isMobile}
                // showQuickJumper
                pageSize={this.pageSize}
                current={this.current}
                total={this.total}
                onChange={this.onChange} />
        )
    }
}


/**
 * 行 操作
 * @param frameworkComponents 
 */
function getColumnDefsAction(frameworkComponents) {
    if (lodash.has(frameworkComponents, 'RowAction')) {
        return [{
            headerName: 'action_name',
            field: 'RowAction',
            cellRenderer: 'RowAction',
            pinned: React.AppConfig.userAgent.isMobile ? false : 'right',
            sortable: false,
            suppressMenu: true,
            suppressColumnsToolPanel: true,
        }]
    }
    return []
}
/**
 * 行 头部选择框
 * @param checkboxSelection 
 */
function getColumnDefsCheckbox(checkboxSelection): (ColGroupDef | ColDef)[] {
    if (lodash.eq(checkboxSelection, false)) {
        return []
    }
    const width = { material: 65, alpine: 50, balham: 40 }[theme]
    return [{
        pinned: React.AppConfig.userAgent.isMobile ? false : "left",
        rowDrag: false,
        dndSource: false,
        lockPosition: true,
        suppressMenu: true,
        suppressSizeToFit: true,
        suppressMovable: true,
        suppressNavigable: true,
        suppressCellFlash: true,
        enableRowGroup: false,
        enablePivot: false,
        enableValue: false,
        editable: false,
        suppressColumnsToolPanel: true,
        filter: false,
        resizable: false,
        checkboxSelection: true,
        headerCheckboxSelection: true,
        width: width,
        minWidth: width,
        maxWidth: width,
    }]
}

// packages/vuejs/components/page/grid/index.vue
<template>
  <div>
    <div class="w-grid-content" :style="style" ref="gridContent">
      <GridView
        :theme="theme"
        :columnDefs="getColumnDefs"
        :rowData="Pagination.dataSource"
        :gridOptions="options"
      />
    </div>
    <a-divider />
    <Pagination :PageController="PageController" />
  </div>
</template>

<script lang="ts">
import { BasesController } from "@mamba/clients";
import { ColumnApi, GridApi, GridOptions, GridReadyEvent, RowDataChangedEvent } from "ag-grid-community";
import lodash from "lodash";
import { observer } from "mobx-vue";
import { fromEvent, Subscription } from "rxjs";
import { debounceTime } from "rxjs/operators";
import { Component, Inject, Prop, Ref, Vue, Watch } from "vue-property-decorator";
import defaultOptions, { getColumnDefsAction, getColumnDefsCheckbox } from "./defaultOptions";
import framework from "./framework";
import Pagination from "./pagination.vue";
import loading from "./loading.vue";
const Cache = new Map<string, any>();
@observer
@Component({
  components: {
    Pagination,
    // 拆分 包 异步加载
    GridView: () => ({
      component: import('./agGrid.async.vue'),
      loading,
    }),
  },
})
export default class Grid extends Vue {
  // static Cache = new Map<string, any>()
  @Inject() readonly PageController: BasesController;
  @Prop({ default: () => ({}) }) readonly GridOptions: GridOptions;
  @Prop({ default: () => true }) readonly CheckboxSelection: boolean;
  @Ref("gridContent") readonly gridContent: HTMLDivElement;
  theme: "balham" | "alpine" | "material" = "material";
  style = { height: "500px" };
  GridApi: GridApi = null;
  ColumnApi: ColumnApi = null;
  ResizeEvent: Subscription;
  LanguagesEvent: Subscription;
  isAutoSizeColumn = true;
  pageKey = '';
  get Pagination() {
    return this.PageController.Pagination;
  }
  // get columnDefs() {
  //   return this.GridOptions.columnDefs
  // }
  get getColumnDefs() {
    return lodash.compact(lodash.concat(
      getColumnDefsCheckbox(this.CheckboxSelection, this.theme),
      this.GridOptions.columnDefs,
      getColumnDefsAction(this.GridOptions.frameworkComponents)
    ));
  }

  get options(): GridOptions {
    const { frameworkComponents = {}, ...gridOptions } = this.GridOptions;
    const options: GridOptions = lodash.assign(
      {
        frameworkComponents: lodash.assign(
          {},
          frameworkComponents,
          framework
        ),
        // 行数据的 id
        getRowNodeId: (data) => lodash.get(data, this.PageController.options.dataKey),
      },
      defaultOptions(this.$i18n as any),
      gridOptions,
      this.GridEvents
    );
    return options;
  }
  get GridEvents(): GridOptions {
    return {
      onSortChanged: (event) => {
        const SortModel = lodash.head(event.api.getSortModel());
        // console.log("LENG ~ Grid ~ getGridEvents ~ event", SortModel)
        const sory = SortModel && SortModel.sort ? { Direction: lodash.capitalize(SortModel.sort), Property: SortModel.colId } : {}
        this.Pagination.onLoad({ current: 1 })
        lodash.invoke(this.GridOptions, "onSortChanged", event);
      },
      // 数据选择
      onSelectionChanged: (event) => {
        this.Pagination.onSelectChange(
          event.api.getSelectedRows()
        );
        lodash.invoke(this.GridOptions, "onSelectionChanged", event);
      },
      // 初始化完成
      onGridReady: (event: GridReadyEvent) => {
        this.GridApi = event.api;
        this.ColumnApi = event.columnApi;
        event.api.sizeColumnsToFit();
        if (this.Pagination.loading) {
          this.GridApi.showLoadingOverlay();
        }
        lodash.invoke(this.GridOptions, "onGridReady", event);
        this.onReckon()
      },
      // onBodyScroll: (event) => {
      //   // console.log("LENG ~ extends ~ event", event.api);
      // },
      // 数据更新
      onRowDataChanged: lodash.debounce((event: RowDataChangedEvent) => {
        if (this.isAutoSizeColumn && this.Pagination.dataSource.length > 0) {
          event.columnApi.autoSizeColumn("RowAction");
          // event.api.sizeColumnsToFit();
          this.isAutoSizeColumn = false;
        }
        lodash.invoke(this.GridOptions, "onRowDataChanged", event);
      }, 300),
    }
  };
  /**
   * 计算 表格高度
   */
  onReckon() {
    let height = 500;
    height = window.innerHeight - this.gridContent.offsetTop - 150;
    this.style.height = height + "px";
    if (this.AppConfig.userAgent.isMobile) {
      this.style.height = "70vh";
    }
    Cache.set(this.pageKey, this.style.height)
  }
  @Watch("Pagination.loading")
  onLoading(val, old) {
    console.log("LENG ~ Grid ~ onLoading ~ val", val)
    if (this.GridApi) {
      if (val) {
        this.GridApi.showLoadingOverlay();
      } else {
        this.GridApi.hideOverlay();
      }
    }
  }
  @Watch("$route.path")
  onRoute(val, old) {
    if (lodash.eq(val, this.pageKey)) {
      // this.autoSizeColumn()
    }
  }
  // autoSizeColumn = lodash.debounce(() => {
  //   this.onReckon()
  //   this.GridApi?.sizeColumnsToFit();
  //   this.ColumnApi?.autoSizeColumn("RowAction");
  // }, 300)
  created() {
    this.pageKey = this.$route.path
    if (Cache.has(this.pageKey)) {
      this.style.height = Cache.get(this.pageKey);
    }
  }
  mounted() {
    this.$nextTick(() => this.onReckon())
    this.ResizeEvent = fromEvent(window, "resize")
      .pipe(debounceTime(200))
      .subscribe(this.onReckon);
    // this.LanguagesEvent = fromEvent(window, "languages")
    //   .pipe(debounceTime(200))
    //   .subscribe(obx => {
    //     this.ColumnApi?.autoSizeColumn("RowAction");
    //   })
  }
  unmounted() {
    this.ResizeEvent && this.ResizeEvent.unsubscribe();
    this.ResizeEvent = undefined;
  }
}
</script>
<style  lang="less">
.w-grid-content {
  height: 500px;
  transition: all 0.2s;
}
</style>
