// packages/weapp/src/pages/details/index.tsx
import { View } from '@tarojs/components'
import { observer } from 'mobx-react'
import { Component } from 'react'
import './index.less'

@observer
class Index extends Component {
  get Store() {
    return this.$Store.Test
  }
  componentWillMount() { }

  componentDidMount() {
    this.Store.onFind(this.$Router.params)
  }

  componentWillUnmount() {
    this.Store.Details.clear()
  }

  componentDidShow() { }

  componentDidHide() { }
  render() {
    return (
      <View className='index'>
        <van-card
          tag={this.Store.entity?.gender}
          desc={this.Store.entity?.introduce}
          title={this.Store.entity?.name}
          thumb={this.Store.entity?.avatar}
        />
      </View>
    )
  }
}

export default Index

// packages/mobile/pages/example/details/index.vue
<template>
  <van-skeleton title avatar :row="3" :loading="PageController.loading">
    <van-card
      :desc="PageController.entity.introduce"
      :title="PageController.entity.name"
      :thumb="PageController.entity.avatar"
    />
  </van-skeleton>
</template>
<script lang="ts">
import { Observer } from "mobx-vue";
import { Component, Vue } from "vue-property-decorator";
@Observer
@Component({
  layout: 'navBar',
  components: {}
})
export default class extends Vue {
  get PageController() {
    return this.$store.Example.Details
  }
  created() {
    this.PageController.onLoad(this.$route.query)
  }
  mounted() { }
  updated() { }
  destroyed() { }
}
</script>
<style lang="less">
</style>
